# Generated by Django 4.2.7 on 2024-08-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_refresh_token_alter_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
